name: CD
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: copy files via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: app
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        env:
          TRAEFIK_HOSTNAME: ${{ env.TRAEFIK_HOSTNAME }}
          TRAEFIK_ACME_EMAIL: ${{ env.TRAEFIK_ACME_EMAIL }}
          TRAEFIK_LOG_LEVEL: ${{ env.TRAEFIK_LOG_LEVEL }}
          SHA: ${{ github.sha }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: TRAEFIK_HOSTNAME,TRAEFIK_ACME_EMAIL,TRAEFIK_LOG_LEVEL,SHA
          script: |
            echo "TRAEFIK_ACME_EMAIL=$TRAEFIK_ACME_EMAIL" > app/.env
            echo "TRAEFIK_HOSTNAME=$TRAEFIK_HOSTNAME" >> app/.env
            echo "TRAEFIK_LOG_LEVEL=$TRAEFIK_LOG_LEVEL" >> app/.env
            echo "SHA=$SHA" >> app/.env
            docker compose -f app/docker-compose.yml up -d

